# Generated by Django 5.2.1 on 2025-05-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialidadeMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Anestesista, Pediatra, Cardiologista...', max_length=200, unique=True, verbose_name='Especialidade Médica')),
                ('criado_em', models.DateTimeField(auto_now_add=True, help_text='Data de criação', verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, help_text='Data de atualização', verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Especialidade Médica',
                'verbose_name_plural': 'Especialidades Médicas',
            },
        ),
    ]
