# Generated by Django 5.2.1 on 2025-05-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da medico', max_length=200, verbose_name='Nome')),
                ('telefone', models.CharField(help_text='Ex: XXXXXX-XXXX', max_length=11, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, help_text='Email da medico', max_length=100, unique=True, verbose_name='Email')),
                ('data_nascimento', models.DateField(help_text='Data de nascimento', verbose_name='Data de nascimento')),
                ('cpf', models.CharField(help_text='EX: XXXXXXXXX', max_length=11, unique=True, verbose_name='CPF')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('inativo', 'inativo')], default='Ativo', help_text='Status do medico', max_length=10, verbose_name='Status')),
                ('crm', models.CharField(help_text='Ex: CRM/UF XXXXXX', max_length=13, unique=True, verbose_name='CRM')),
                ('criado_em', models.DateTimeField(auto_now_add=True, help_text='Data de criação', verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, help_text='Data de atualização', verbose_name='Atualizado em')),
                ('especialidades', models.ManyToManyField(to='prontuario.especialidademedica')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
            },
        ),
    ]
